//=========================================================================================================================================
//This data quizzes users about swords, style, country of origin and time period
//=========================================================================================================================================

var data = [
                {SwordName: "Chokuto",         Style: "Single-Edged Straight Sword", Country: "Japan",          Century: 10th,  Description: "The Chokutō was among the earliest in the history of Japanese sword-forging as its basic style and forging techniques probably originated in ancient China and were brought to Japan by way of Korea in the 3rd centuries" },
                {SwordName: "Tsurugi",         Style: "Double-Edged Straight Sword", Country: "Japan",          Century: 5th,  Description: "The Tsurugi was similar in style and based on the Chinese Jian Sword" },
                {SwordName: "Tachi",         Style: "Single-Edged Curved Sword", Country: "Japan",          Century: 13th,  Description: "The Tachi sword was typically worn by the Samurai class and its development preceded the Katana. The blade had a higher degree of curvature than the later Katana" },
                {SwordName: "Kodachi",         Style: "Single-Edged Curved Sword", Country: "Japan",          Century: 12th,  Description: "The Kodachi was a shorter version of the Tachi sword but generally sword and used in a similar manner" },
                {SwordName: "Chokuto",         Style: "Straight", Country: "Japan",          Century: 10th,  Description: "Chokutō was among the earliest in the history of Japanese sword-forging as its basic style and forging techniques probably originated in ancient China and were brought to Japan by way of Korea in the 3rd centuries" },
                {SwordName: "Chokuto",         Style: "Straight", Country: "Japan",          Century: 10th,  Description: "Chokutō was among the earliest in the history of Japanese sword-forging as its basic style and forging techniques probably originated in ancient China and were brought to Japan by way of Korea in the 3rd centuries" },
                {SwordName: "Chokuto",         Style: "Straight", Country: "Japan",          Century: 10th,  Description: "Chokutō was among the earliest in the history of Japanese sword-forging as its basic style and forging techniques probably originated in ancient China and were brought to Japan by way of Korea in the 3rd centuries" },
                {SwordName: "Chokuto",         Style: "Straight", Country: "Japan",          Century: 10th,  Description: "Chokutō was among the earliest in the history of Japanese sword-forging as its basic style and forging techniques probably originated in ancient China and were brought to Japan by way of Korea in the 3rd centuries" },
                {SwordName: "Chokuto",         Style: "Straight", Country: "Japan",          Century: 10th,  Description: "Chokutō was among the earliest in the history of Japanese sword-forging as its basic style and forging techniques probably originated in ancient China and were brought to Japan by way of Korea in the 3rd centuries" },
                {SwordName: "Chokuto",         Style: "Straight", Country: "Japan",          Century: 10th,  Description: "Chokutō was among the earliest in the history of Japanese sword-forging as its basic style and forging techniques probably originated in ancient China and were brought to Japan by way of Korea in the 3rd centuries" },
             
            ];